### ISSUE TITLE
Error while running android

### ISSUE THREAD

**Issue by yasicmd** [trashgenerator/fifteen#1]
The error is as shown below.....

Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Could not install the app on the device, see the error above.

**Comment by nosovsh** [comment]
Have you tried running it using Android Studio?

**Comment by grigio** [comment]
+1 any workaround for this?

**Comment by grigio** [comment]
apparently I just had to install gradle
`brew install gradle`
and run again
`react-native run-android`

**Comment by nosovsh** [comment]
So now is it working?

**Comment by yasicmd** [comment]
fixed
